// src/account-menu.tsx
import { useEffect, useRef, useState } from 'react';

/**
 * React twin of f2-account-menu (Angular). Top-right "account coin" —
 * compact circular avatar that EXPANDS ON HOVER to reveal an identity
 * pill next to the coin (First Last on top, email as smaller subtext),
 * and OPENS ON CLICK into a dropdown carrying Exchange Agreements /
 * Change password / Sign out.
 *
 * Hover-to-reveal is the canonical contract: identity is always one
 * mouse move away without spending header real estate on a permanent
 * label. Focus also expands so keyboard users get the same affordance.
 *
 * When firstName/lastName are absent the pill falls back to email-only.
 *
 * Self-contained — no external icon or dropdown library.
 */

/**
 * Optional consumer-injected dropdown items. Each renders between
 * Exchange Agreements and Change password. Items with `href` render
 * as <a>; items with `onClick` render as <button>. Consumers gate
 * visibility on their own (pass an empty array to hide all). Used
 * by f2-members to surface its admin-only "Integration" link inside
 * the menu rather than as a sibling header link.
 */
export interface AccountMenuItem {
  label: string;
  href?: string;
  onClick?: () => void;
}

export interface AccountMenuProps {
  agreementUrl?: string | null;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  customItems?: AccountMenuItem[];
  onSignOut: () => void;
  onChangePassword: () => void;
}

/**
 * Filter the `email` prop down to "only real emails". Consumers
 * historically did `user?.email ?? user?.username ?? null` as a
 * fallback chain — but Username on auto-username Cognito pools IS
 * the sub UUID, so the chip ended up showing
 * "64686498-4081-70da-..." which reads as a random ID to the user.
 * Same shape ID can also leak from a bundle's user.email field if
 * the mint side fell back to Username.
 *
 * Single enforcement point: any email value that doesn't contain
 * '@' is treated as null. Consumers can pass whatever; the chip
 * NEVER shows non-email-shaped values.
 *
 * Per the standing rule feedback_never_display_username_uuid.
 */
function safeEmail(value: string | null | undefined): string | null {
  if (!value) return null;
  const s = String(value).trim();
  if (!s || !s.includes('@')) return null;
  return s;
}

export function AccountMenu({ agreementUrl, email: emailIn, firstName, lastName, customItems, onSignOut, onChangePassword }: AccountMenuProps) {
  const email = safeEmail(emailIn);
  const [hover, setHover] = useState(false);
  const [focus, setFocus] = useState(false);
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;
    const onDoc = (ev: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(ev.target as Node)) setOpen(false);
    };
    const onEsc = (ev: KeyboardEvent) => {
      if (ev.key === 'Escape') setOpen(false);
    };
    document.addEventListener('click', onDoc);
    document.addEventListener('keydown', onEsc);
    return () => {
      document.removeEventListener('click', onDoc);
      document.removeEventListener('keydown', onEsc);
    };
  }, [open]);

  const displayName = [firstName || '', lastName || ''].map(s => s.trim()).filter(Boolean).join(' ');
  const hasIdentity = !!(email || displayName);

  // Pill is visible while the user is hovering, focused, OR has the
  // menu open. Keeping it open during the dropdown means the identity
  // header inside the menu can be dropped without losing context.
  const expanded = hasIdentity && (hover || focus || open);

  // Per-customer brand-aware colors. Each value falls back to the pre-
  // theming hex so SPAs without a Customer.branding subdoc render exactly
  // as before. Light-on-dark dropdown was the original f2 default and
  // still matches dark-themed customers (hima); light-themed customers
  // (option-pit cream + lime) get the lime accent on the coin/pill and
  // their panel-to color in the dropdown sheet. Mike 2026-06-27.
  const itemBase = {
    display: 'block' as const,
    padding: '10px 16px',
    fontSize: 14,
    color: 'var(--brand-text-primary, #e5e7eb)',
    textDecoration: 'none',
    background: 'transparent',
    border: 0,
    cursor: 'pointer',
  };
  // rgba-fallback variants keep the original subtle overlay look on
  // brands that don't supply panel-bg-hover / panel-border, and inherit
  // the brand-tinted color on those that do.
  const itemHoverBg = 'var(--brand-panel-bg-hover, rgba(255,255,255,0.08))';
  const sheetBorder = 'var(--brand-panel-border, rgba(255,255,255,0.08))';

  return (
    <div
      ref={wrapRef}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{ position: 'relative', display: 'inline-flex', alignItems: 'center' }}
      data-f2-account-menu
    >
      {hasIdentity && (
        <span
          aria-hidden={!expanded}
          style={{
            maxWidth: expanded ? 320 : 0,
            opacity: expanded ? 1 : 0,
            paddingLeft: expanded ? 12 : 0,
            paddingRight: expanded ? 12 : 0,
            paddingTop: 6,
            paddingBottom: 6,
            marginRight: expanded ? 8 : 0,
            overflow: 'hidden',
            whiteSpace: 'nowrap',
            textOverflow: 'ellipsis',
            background: 'var(--brand-accent, white)',
            color: 'var(--brand-accent-text, #11314D)',
            lineHeight: 1.1,
            borderRadius: 9999,
            transition: 'max-width 200ms ease, opacity 150ms ease, padding 200ms ease, margin 200ms ease',
            pointerEvents: expanded ? 'auto' : 'none',
            display: 'inline-flex',
            flexDirection: 'column',
            alignItems: 'flex-end',
          }}
        >
          {displayName && (
            <span style={{ fontSize: 13, fontWeight: 600 }}>{displayName}</span>
          )}
          {email && (
            <span
              style={{
                fontSize: displayName ? 11 : 13,
                fontWeight: displayName ? 400 : 500,
                opacity: displayName ? 0.7 : 1,
              }}
            >
              {email}
            </span>
          )}
        </span>
      )}
      <button
        type="button"
        onClick={(ev) => {
          ev.stopPropagation();
          setOpen((v) => !v);
        }}
        onFocus={() => setFocus(true)}
        onBlur={() => setFocus(false)}
        aria-expanded={open}
        aria-haspopup="true"
        aria-label={displayName ? `Open account menu for ${displayName}` : email ? `Open account menu for ${email}` : 'Open account menu'}
        title={displayName || email || undefined}
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 32,
          height: 32,
          borderRadius: 9999,
          background: 'var(--brand-accent, white)',
          border: 0,
          padding: 0,
          cursor: 'pointer',
        }}
      >
        <svg width={22} height={22} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          {/* The figure silhouette inside the coin uses --brand-accent-text
              for the bg circle (the same dark color paired with the lime/
              white coin bg above), and --brand-accent for the figure
              itself so it inherits the coin tone — keeps the contrast
              ratio identical to the default white-on-navy design when
              swapped with any brand pair. */}
          <circle cx="12" cy="12" r="11" fill="var(--brand-accent-text, #11314D)" />
          <circle cx="12" cy="9.5" r="3.25" fill="var(--brand-accent, white)" />
          <path d="M5.5 19c1.2-3.2 3.7-4.75 6.5-4.75S17.3 15.8 18.5 19" stroke="var(--brand-accent, white)" strokeWidth={1.6} strokeLinecap="round" fill="none" />
        </svg>
      </button>

      {open && (
        <div
          role="menu"
          style={{
            position: 'absolute',
            top: 'calc(100% + 8px)',
            right: 0,
            zIndex: 9999,
            minWidth: 240,
            background: 'var(--brand-panel-to, #0E1019)',
            border: `1px solid ${sheetBorder}`,
            borderRadius: 4,
            boxShadow: '0 6px 16px rgba(0,0,0,0.4)',
            overflow: 'hidden',
          }}
        >
          {(displayName || email) && (
            <div
              style={{
                padding: '10px 16px',
                borderBottom: `1px solid ${sheetBorder}`,
                background: 'var(--brand-panel-bg-hover, rgba(255,255,255,0.03))',
              }}
            >
              {displayName && (
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--brand-text-primary, #f3f4f6)', lineHeight: 1.2 }}>{displayName}</div>
              )}
              {email && (
                <div
                  style={{
                    fontSize: displayName ? 11 : 13,
                    color: displayName ? 'var(--brand-text-muted, #9ca3af)' : 'var(--brand-text-primary, #e5e7eb)',
                    marginTop: displayName ? 2 : 0,
                    lineHeight: 1.2,
                    wordBreak: 'break-all',
                  }}
                >
                  {email}
                </div>
              )}
            </div>
          )}
          {agreementUrl && (
            <a
              href={agreementUrl}
              target="_blank"
              rel="noopener noreferrer"
              role="menuitem"
              onClick={() => setOpen(false)}
              style={itemBase}
              onMouseOver={(e) => (e.currentTarget.style.background = itemHoverBg)}
              onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
            >
              Exchange Agreements
            </a>
          )}
          {(customItems || []).map((item, idx) =>
            item.href ? (
              <a
                key={`ci-${idx}`}
                href={item.href}
                role="menuitem"
                onClick={() => setOpen(false)}
                style={itemBase}
                onMouseOver={(e) => (e.currentTarget.style.background = itemHoverBg)}
                onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
              >
                {item.label}
              </a>
            ) : (
              <button
                key={`ci-${idx}`}
                type="button"
                role="menuitem"
                onClick={() => {
                  setOpen(false);
                  item.onClick?.();
                }}
                style={{ ...itemBase, width: '100%', textAlign: 'left' }}
                onMouseOver={(e) => (e.currentTarget.style.background = itemHoverBg)}
                onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
              >
                {item.label}
              </button>
            )
          )}
          <button
            type="button"
            role="menuitem"
            onClick={() => {
              setOpen(false);
              onChangePassword();
            }}
            style={{ ...itemBase, width: '100%', textAlign: 'left' }}
            onMouseOver={(e) => (e.currentTarget.style.background = itemHoverBg)}
            onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
          >
            Change password
          </button>
          <button
            type="button"
            role="menuitem"
            onClick={() => {
              setOpen(false);
              onSignOut();
            }}
            style={{ ...itemBase, width: '100%', textAlign: 'left', borderTop: `1px solid ${sheetBorder}` }}
            onMouseOver={(e) => (e.currentTarget.style.background = itemHoverBg)}
            onMouseOut={(e) => (e.currentTarget.style.background = 'transparent')}
          >
            Sign out
          </button>
        </div>
      )}
    </div>
  );
}

// src/account-menu.component.ts
import { Component, Input, Output, EventEmitter, HostListener, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Canonical Angular standalone component for the top-right "account
 * coin" + dropdown. Replaces the inline `id="user-menu-button"` HTML
 * duplicated across theo-trade, option-pit, alpha-shark, delphi-signal,
 * mta, quant-pivot-pro, f2-admin, strat-alerts. Single source of truth
 * for the coin shape, dropdown layout, and item ordering.
 *
 * Behavior contract (matches React twin in account-menu.tsx):
 *   - HOVER (mouseenter / focus) → coin expands to reveal an identity
 *     pill on its left. When firstName/lastName are present the pill
 *     shows "First Last" on top with the email as a smaller subtext;
 *     otherwise the pill collapses to just the email. The pill collapses
 *     on mouseleave/blur unless the dropdown is open.
 *   - CLICK → dropdown with Exchange Agreements / Change password /
 *     Sign out items.
 *
 * Why two-line identity: the underlying Cognito bundle sometimes lands
 * with the Username (sub UUID) where the email should be — surfacing
 * "64686498-4081-70da-7dab-..." as the only label is unreadable. Even
 * when the email is correct, the human-readable name is the better
 * primary label. Falling back to email-only keeps the pill useful when
 * the consumer hasn't wired identity through yet.
 */
@Component({
  standalone: true,
  selector: 'f2-account-menu',
  imports: [CommonModule],
  template: `
    <div
      style="position:relative;display:inline-flex;align-items:center"
      data-f2-account-menu
      (mouseenter)="hover = true"
      (mouseleave)="hover = false"
    >
      <span
        *ngIf="hasIdentity"
        [attr.aria-hidden]="!expanded"
        [style.max-width.px]="expanded ? 320 : 0"
        [style.opacity]="expanded ? 1 : 0"
        [style.padding-left.px]="expanded ? 12 : 0"
        [style.padding-right.px]="expanded ? 12 : 0"
        [style.margin-right.px]="expanded ? 8 : 0"
        [style.pointer-events]="expanded ? 'auto' : 'none'"
        style="padding-top:6px;padding-bottom:6px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;background:var(--brand-accent, white);color:var(--brand-accent-text, #11314D);line-height:1.1;border-radius:9999px;transition:max-width 200ms ease,opacity 150ms ease,padding 200ms ease,margin 200ms ease;display:inline-flex;flex-direction:column;align-items:flex-end"
      >
        <span *ngIf="displayName" style="font-size:13px;font-weight:600">{{ displayName }}</span>
        <span *ngIf="email" [style.font-size.px]="displayName ? 11 : 13" [style.font-weight]="displayName ? 400 : 500" [style.opacity]="displayName ? 0.7 : 1">{{ email }}</span>
      </span>
      <button
        type="button"
        (click)="toggle($event)"
        (focus)="focus = true"
        (blur)="focus = false"
        [attr.aria-expanded]="open"
        aria-haspopup="true"
        [attr.aria-label]="ariaLabel"
        [attr.title]="displayName || email || null"
        style="display:flex;align-items:center;justify-content:center;width:32px;height:32px;border-radius:9999px;background:var(--brand-accent, white);border:0;padding:0;cursor:pointer"
      >
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <circle cx="12" cy="12" r="11" [attr.fill]="'var(--brand-accent-text, #11314D)'"/>
          <circle cx="12" cy="9.5" r="3.25" [attr.fill]="'var(--brand-accent, white)'"/>
          <path d="M5.5 19c1.2-3.2 3.7-4.75 6.5-4.75S17.3 15.8 18.5 19" [attr.stroke]="'var(--brand-accent, white)'" stroke-width="1.6" stroke-linecap="round" fill="none"/>
        </svg>
      </button>

      <div
        *ngIf="open"
        role="menu"
        style="position:absolute;top:calc(100% + 8px);right:0;z-index:9999;min-width:240px;background:var(--brand-panel-to, #0E1019);border:1px solid var(--brand-panel-border, rgba(255,255,255,0.08));border-radius:4px;box-shadow:0 6px 16px rgba(0,0,0,0.4);overflow:hidden"
      >
        <div
          *ngIf="displayName || email"
          style="padding:10px 16px;border-bottom:1px solid var(--brand-panel-border, rgba(255,255,255,0.08));background:var(--brand-panel-bg-hover, rgba(255,255,255,0.03))"
        >
          <div *ngIf="displayName" style="font-size:13px;font-weight:600;color:var(--brand-text-primary, #f3f4f6);line-height:1.2">{{ displayName }}</div>
          <div *ngIf="email" [style.font-size.px]="displayName ? 11 : 13" [style.color]="displayName ? 'var(--brand-text-muted, #9ca3af)' : 'var(--brand-text-primary, #e5e7eb)'" [style.margin-top.px]="displayName ? 2 : 0" style="line-height:1.2;word-break:break-all">{{ email }}</div>
        </div>
        <a
          *ngIf="agreementUrl"
          [href]="agreementUrl"
          target="_blank"
          rel="noopener noreferrer"
          role="menuitem"
          (click)="open = false"
          style="display:block;padding:10px 16px;font-size:14px;color:var(--brand-text-primary, #e5e7eb);text-decoration:none;cursor:pointer"
          onmouseover="this.style.background='var(--brand-panel-bg-hover, rgba(255,255,255,0.08))'"
          onmouseout="this.style.background='transparent'"
        >Exchange Agreements</a>
        <ng-container *ngFor="let item of customItems; trackBy: trackCustomItem">
          <a *ngIf="item.href"
            [href]="item.href"
            role="menuitem"
            (click)="open = false"
            style="display:block;padding:10px 16px;font-size:14px;color:var(--brand-text-primary, #e5e7eb);text-decoration:none;cursor:pointer"
            onmouseover="this.style.background='var(--brand-panel-bg-hover, rgba(255,255,255,0.08))'"
            onmouseout="this.style.background='transparent'"
          >{{ item.label }}</a>
          <button *ngIf="!item.href"
            type="button"
            role="menuitem"
            (click)="onCustomItem(item)"
            style="display:block;width:100%;text-align:left;padding:10px 16px;font-size:14px;color:var(--brand-text-primary, #e5e7eb);background:transparent;border:0;cursor:pointer"
            onmouseover="this.style.background='var(--brand-panel-bg-hover, rgba(255,255,255,0.08))'"
            onmouseout="this.style.background='transparent'"
          >{{ item.label }}</button>
        </ng-container>
        <button
          type="button"
          role="menuitem"
          (click)="onChangePassword()"
          style="display:block;width:100%;text-align:left;padding:10px 16px;font-size:14px;color:var(--brand-text-primary, #e5e7eb);background:transparent;border:0;cursor:pointer"
          onmouseover="this.style.background='var(--brand-panel-bg-hover, rgba(255,255,255,0.08))'"
          onmouseout="this.style.background='transparent'"
        >Change password</button>
        <button
          type="button"
          role="menuitem"
          (click)="onSignOut()"
          style="display:block;width:100%;text-align:left;padding:10px 16px;font-size:14px;color:var(--brand-text-primary, #e5e7eb);background:transparent;border:0;border-top:1px solid var(--brand-panel-border, rgba(255,255,255,0.08));cursor:pointer"
          onmouseover="this.style.background='var(--brand-panel-bg-hover, rgba(255,255,255,0.08))'"
          onmouseout="this.style.background='transparent'"
        >Sign out</button>
      </div>
    </div>
  `,
})
/**
 * Optional consumer-injected dropdown items. Each renders between
 * Exchange Agreements and Change password. Items with `href` render
 * as <a>; items with `clicked` callback render as <button>.
 */
export interface AccountMenuItem {
  label: string;
  href?: string;
  clicked?: () => void;
}

export class AccountMenuComponent {
  @Input() agreementUrl: string | null = null;
  // Backing field for the email Input; the public setter sanitizes
  // to enforce "only @-shaped values are displayed". Consumers
  // historically fell back to user.username when email was empty,
  // and Username on auto-username Cognito pools IS the sub UUID
  // (e.g. "64686498-4081-70da-..."), which lands in the chip as a
  // random ID number. Single enforcement point: any non-@-shaped
  // input is treated as null. Per feedback_never_display_username
  // _uuid.
  private _email: string | null = null;
  @Input() set email(value: string | null) {
    if (!value) { this._email = null; return; }
    const s = String(value).trim();
    this._email = (!s || !s.includes('@')) ? null : s;
  }
  get email(): string | null { return this._email; }
  @Input() firstName: string | null = null;
  @Input() lastName: string | null = null;
  @Input() customItems: AccountMenuItem[] = [];
  @Output() signOut = new EventEmitter<void>();
  @Output() changePassword = new EventEmitter<void>();

  open = false;
  hover = false;
  focus = false;

  trackCustomItem(_idx: number, item: AccountMenuItem) {
    return item.label;
  }

  onCustomItem(item: AccountMenuItem) {
    this.open = false;
    if (typeof item.clicked === 'function') item.clicked();
  }

  constructor(private host: ElementRef<HTMLElement>) {}

  get displayName(): string {
    const f = (this.firstName || '').trim();
    const l = (this.lastName || '').trim();
    const combined = [f, l].filter(Boolean).join(' ');
    return combined || '';
  }

  get hasIdentity(): boolean {
    return !!(this.email || this.displayName);
  }

  get expanded(): boolean {
    return !!(this.hasIdentity && (this.hover || this.focus || this.open));
  }

  get ariaLabel(): string {
    const label = this.displayName || this.email;
    return label ? `Open account menu for ${label}` : 'Open account menu';
  }

  toggle(ev: MouseEvent) {
    ev.stopPropagation();
    this.open = !this.open;
  }

  onSignOut() {
    this.open = false;
    this.signOut.emit();
  }

  onChangePassword() {
    this.open = false;
    this.changePassword.emit();
  }

  // Click-outside close. Cheaper than wiring an overlay; the menu is
  // small and short-lived so the document listener cost is negligible.
  @HostListener('document:click', ['$event'])
  onDocClick(ev: MouseEvent) {
    if (!this.open) return;
    if (!this.host.nativeElement.contains(ev.target as Node)) {
      this.open = false;
    }
  }

  // Esc closes — keyboard parity with the underlying dropdown contract.
  @HostListener('document:keydown.escape')
  onEsc() {
    this.open = false;
  }
}
