// src/data-tier-banner.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Single canonical Angular standalone component for the company/customer
 * data-tier banner. Every scanner SPA imports this so the COPY + COLORS
 * stay in lockstep — drift (mta's red+pulse one-off, etc.) is no
 * longer possible.
 *
 * Wiring contract:
 *   1. Caller computes `mode` from `resolveDataTier({...}).bannerMode`
 *   2. Renders `<f2-data-tier-banner [mode]="dataTierMode"></f2-data-tier-banner>`
 *   3. Place as the FIRST CHILD of the app shell so it pushes header
 *      down rather than overlaying (no position:fixed/absolute/sticky).
 *
 * Inline styles (NOT Tailwind classes) so the component renders the
 * same in every SPA regardless of Tailwind config / content path.
 *
 * The auth/admin/live-data resolution remains per-SPA (depends on each
 * SPA's local auth service) — only the visual presentation is shared.
 */
@Component({
  standalone: true,
  selector: 'f2-data-tier-banner',
  imports: [CommonModule],
  template: `
    <ng-container *ngIf="mode as m">
      <div
        [style.background]="bg(m)"
        style="width:100%;padding:8px 16px;text-align:center;color:white;font-size:14px;font-weight:500;box-shadow:0 2px 4px rgba(0,0,0,0.15)"
        role="status"
        aria-live="polite"
      >{{ text(m) }}</div>
    </ng-container>
  `,
})
export class DataTierBannerComponent {
  @Input() mode: 'delayed' | 'realtime' | 'disabled' | null = null;

  bg(m: 'delayed' | 'realtime' | 'disabled'): string {
    if (m === 'delayed') return '#f59e0b';
    if (m === 'realtime') return '#2563eb';
    return '#dc2626';
  }

  text(m: 'delayed' | 'realtime' | 'disabled'): string {
    if (m === 'delayed') return 'Delayed Data Mode — F2 has switched all scanners to delayed feeds.';
    if (m === 'realtime') return 'Realtime Data Mode — all users serving live data.';
    return 'Service Disabled — F2 has temporarily disabled scanners.';
  }
}

// src/data-tier-banner.tsx
import { useEffect, useState } from 'react';
import { resolveDataTier } from './agreements.js';

/**
 * React equivalent of f2-data-tier-banner (Angular). Single canonical
 * implementation for every React SPA (members, alpha-shark-flow,
 * trend-labs-react) so the COPY + COLORS stay in lockstep with the
 * Angular SPAs.
 *
 * Self-contained: calls resolveDataTier internally. The caller only
 * passes auth context (`isAdmin`, optional `userLiveAccess`). Render
 * as the FIRST CHILD of the app root so it pushes content down rather
 * than overlaying.
 */

type Mode = 'delayed' | 'realtime' | 'disabled' | null;

const STYLES: Record<Exclude<Mode, null>, { bg: string; text: string }> = {
  delayed: { bg: '#f59e0b', text: 'Delayed Data Mode — F2 has switched all scanners to delayed feeds.' },
  realtime: { bg: '#2563eb', text: 'Realtime Data Mode — all users serving live data.' },
  disabled: { bg: '#dc2626', text: 'Service Disabled — F2 has temporarily disabled scanners.' },
};

export interface DataTierBannerProps {
  isAdmin: boolean;
  userLiveAccess?: boolean;
}

export function DataTierBanner({ isAdmin, userLiveAccess = false }: DataTierBannerProps) {
  const [mode, setMode] = useState<Mode>(null);

  useEffect(() => {
    let cancelled = false;
    resolveDataTier({ userLiveAccess, isAdmin })
      .then((r: any) => { if (!cancelled) setMode((r?.bannerMode as Mode) ?? null); })
      .catch(() => { if (!cancelled) setMode(null); });
    return () => { cancelled = true; };
  }, [isAdmin, userLiveAccess]);

  if (!mode) return null;
  const cfg = STYLES[mode];
  return (
    <div
      style={{
        width: '100%',
        padding: '8px 16px',
        textAlign: 'center',
        color: 'white',
        fontSize: 14,
        fontWeight: 500,
        boxShadow: '0 2px 4px rgba(0,0,0,0.15)',
        background: cfg.bg,
      }}
      role="status"
      aria-live="polite"
    >
      {cfg.text}
    </div>
  );
}
