// src/session-displaced-banner.tsx
/**
 * IT-F2-391 c/0312c1a7 (Mike, T3 rollout) — fleet-standard displaced-tab
 * banner for the LIVE_SESSIONS single-window enforcement. Rendered above
 * the app when THIS session's live-data slot has been taken by another
 * browser/tab (backend responded 401 + X-F2-Reject-Reason: displaced on
 * the sanitize probe, or set data_tier=delayed_displaced).
 *
 * Fleet contract:
 *   The consumer SPA detects the displaced state (from the sanitize probe
 *   response OR from a socket.io session_displaced event) and toggles
 *   `visible=true`. On click, the banner runs `onReclaim` — canonical
 *   implementation clears sessionStorage.f2_session_id and reloads, so
 *   the fresh mount generates a new id and re-issues X-F2-Claim-Slot:
 *   reclaim, winning the slot back.
 *
 * COPY:
 *   Per Mike's spec: "another session has taken your realtime data — not
 *   start asking them to fill out paperwork all over again that they
 *   already have filled out and has been approved". This banner is
 *   distinct from ExchangeAgreementsBanner (which routes on missing /
 *   pending / declined agreement state). Consumer should suppress the
 *   ExchangeAgreementsBanner when displaced=true — displacement is not
 *   an agreement-completion issue.
 *
 * STYLING:
 *   Orange (#c2410c ↔ #9a3412) pulse at 1.6s, matching FinderView's
 *   fn-delayed.displaced chip color palette so the banner visually
 *   binds to the chip.
 *
 * Kept inline-styles + a scoped keyframe so consumer SPAs that
 * don't use Tailwind (Angular apps) render identically.
 */

export interface SessionDisplacedBannerProps {
  /** Show the banner. Consumer sets true when the SPA detects
   *  data_tier=delayed_displaced OR receives a session_displaced WS event. */
  visible: boolean;
  /** Handler for the click-to-reclaim action. Canonical implementation:
   *  clear sessionStorage.f2_session_id then window.location.reload(). */
  onReclaim: () => void;
  /** Optional override for the "ANOTHER SESSION IS LIVE" strong label. */
  label?: string;
  /** Optional override for the plain-text explanation. */
  message?: string;
}

const DEFAULT_LABEL = 'ANOTHER SESSION IS LIVE';
const DEFAULT_MESSAGE = 'Your realtime data seat was taken by another window/browser. Click here to reload and reclaim it.';

// Unique keyframe name so multiple copies of this component on the page
// (unlikely but possible) don't collide. Also avoids clashing with a
// consumer's own `@keyframes pulse`.
const KEYFRAME_NAME = 'f2-session-displaced-pulse';

export function SessionDisplacedBanner({
  visible, onReclaim, label = DEFAULT_LABEL, message = DEFAULT_MESSAGE,
}: SessionDisplacedBannerProps) {
  if (!visible) return null;
  return (
    <>
      <style>{`
        @keyframes ${KEYFRAME_NAME} {
          0%, 100% { background:#c2410c; }
          50%      { background:#9a3412; }
        }
      `}</style>
      <div
        role="alert"
        aria-live="polite"
        onClick={onReclaim}
        style={{
          width: '100%',
          padding: '10px 16px',
          textAlign: 'center',
          color: '#fff',
          fontSize: 14,
          lineHeight: 1.4,
          fontWeight: 500,
          boxShadow: '0 2px 4px rgba(0,0,0,0.15)',
          animation: `${KEYFRAME_NAME} 1.6s ease-in-out infinite`,
          cursor: 'pointer',
        }}
        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') onReclaim(); }}
        tabIndex={0}
      >
        <strong style={{ fontWeight: 700, letterSpacing: '.02em' }}>{label}</strong>
        <span style={{ marginLeft: 8 }}>· {message}</span>
      </div>
    </>
  );
}

// src/session-displaced-banner.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Angular standalone sibling of session-displaced-banner.tsx. Added IT-F2-437
 * (2026-10-06, theo-trade) so Angular adopters get the identical pulsing
 * orange displaced-tab banner.
 *
 * Fleet contract (mirrors session-displaced-banner.tsx):
 *   Consumer SPA detects the displaced state (from the sanitize probe response
 *   OR from a socket.io session_displaced event) and toggles `visible=true`.
 *   On click, the banner emits `reclaim` — canonical implementation clears
 *   sessionStorage.f2_session_id and reloads, so the fresh mount generates a
 *   new id and re-issues X-F2-Claim-Slot: reclaim, winning the slot back.
 *
 * Copy, color palette (#c2410c ↔ #9a3412 pulse at 1.6s), and inline-style
 * approach match the React component 1:1. Keyframe name is unique
 * (`f2-session-displaced-pulse`) so multiple copies on the page cannot
 * collide and consumer `@keyframes pulse` rules cannot clash.
 */

const KEYFRAME_NAME = 'f2-session-displaced-pulse';
const BANNER_CSS = `
@keyframes ${KEYFRAME_NAME} {
  0%, 100% { background:#c2410c; }
  50%      { background:#9a3412; }
}
.f2-sdb-banner{
  width:100%;padding:10px 16px;text-align:center;color:#fff;
  font-size:14px;line-height:1.4;font-weight:500;
  box-shadow:0 2px 4px rgba(0,0,0,0.15);
  animation:${KEYFRAME_NAME} 1.6s ease-in-out infinite;
  cursor:pointer;
}
.f2-sdb-banner strong{font-weight:700;letter-spacing:.02em;}
.f2-sdb-banner .f2-sdb-msg{margin-left:8px;}
`;

@Component({
  standalone: true,
  selector: 'f2-session-displaced-banner',
  imports: [CommonModule],
  styles: [BANNER_CSS],
  template: `
    <ng-container *ngIf="visible">
      <div class="f2-sdb-banner"
        role="alert"
        aria-live="polite"
        tabindex="0"
        (click)="emitReclaim()"
        (keydown)="onKeydown($event)">
        <strong>{{ label }}</strong>
        <span class="f2-sdb-msg">· {{ message }}</span>
      </div>
    </ng-container>
  `,
})
export class SessionDisplacedBannerComponent {
  /** Show the banner. Consumer sets true when the SPA detects
   *  data_tier=delayed_displaced OR receives a session_displaced WS event. */
  @Input() visible = false;
  /** Override for the "ANOTHER SESSION IS LIVE" strong label. */
  @Input() label = 'ANOTHER SESSION IS LIVE';
  /** Override for the plain-text explanation. */
  @Input() message = 'Your realtime data seat was taken by another window/browser. Click here to reload and reclaim it.';
  /** Click (or Enter / Space) emits here. Canonical handler clears
   *  sessionStorage.f2_session_id then window.location.reload(). */
  @Output() reclaim = new EventEmitter<void>();

  emitReclaim() { this.reclaim.emit(); }

  onKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      this.emitReclaim();
    }
  }
}
